language: go

go:
  - 1.13.x
  - 1.14.x

services:
  - docker

before_install:
  - |
    docker run --name kafka --rm -d -p 2181:2181 -p 9092:9092 \
        -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 \
        obsidiandynamics/kafka
  - |
    docker run --name postgres --rm -d -p 5432:5432 \
        -e POSTGRES_HOST_AUTH_METHOD=trust \
        postgres:12
  - go get -u -v all

script:
  - make
  - make int

after_success:
  - bash <(curl -s https://codecov.io/bash)